import {
  Plane,
  Radar,
  Rocket,
  Bomb,
  Crosshair,
  Swords,
  Ship,
  ShieldAlert,
  Megaphone,
  Flame,
  ShieldCheck,
  Siren,
  Wifi,
  Flag,
  Handshake,
  ShieldOff,
  Factory,
  Diamond,
  HelpCircle,
} from "lucide-react";
import type { EventType } from "@/lib/types";

export const EVENT_TYPE_ICON: Record<EventType, React.ComponentType<{ className?: string }>> = {
  airstrike: Plane,
  drone: Radar,
  missile: Rocket,
  explosion: Bomb,
  artillery: Crosshair,
  ground: Swords,
  ground_clash: Swords,
  naval: Ship,
  air_defense: ShieldAlert,
  protest: Megaphone,
  civil_unrest: Megaphone,
  fire: Flame,
  security: ShieldCheck,
  terrorism: Siren,
  cyber: Wifi,
  border: Flag,
  diplomacy: Handshake,
  sanctions: ShieldOff,
  infrastructure: Factory,
  conflict: Diamond,
  other: HelpCircle,
};

export const EVENT_TYPE_LABEL: Record<EventType, string> = {
  airstrike: "Airstrike",
  drone: "Drone",
  missile: "Missile",
  explosion: "Explosion",
  artillery: "Artillery",
  ground: "Ground",
  ground_clash: "Ground Clash",
  naval: "Naval",
  air_defense: "Air Defense",
  protest: "Protest",
  civil_unrest: "Civil Unrest",
  fire: "Fire",
  security: "Security",
  terrorism: "Terrorism",
  cyber: "Cyber",
  border: "Border",
  diplomacy: "Diplomacy",
  sanctions: "Sanctions",
  infrastructure: "Infrastructure",
  conflict: "Conflict",
  other: "Other",
};
