import raw from "@/data/countries.json";

// THE canonical country registry: identity (ISO alpha-2/alpha-3, canonical name, aliases), region and
// subregion, capital, centroid, land-border neighbours and coast/landlocked status. Impact scoring, the
// country pages, search, alerts and briefs all read it; there is no second country list.
// Generated by scripts/build-country-registry.mjs (identity table + Natural Earth borders); recorded
// provenance is in `COUNTRY_REGISTRY_META`. Population is present only where a sourced value exists.

export type CountryRegion = "Europe" | "Middle East" | "Africa" | "Asia" | "Americas" | "Oceania";

export interface CountryRecord {
  /** ISO 3166-1 alpha-2 */
  code: string;
  /** ISO 3166-1 alpha-3 (Kosovo uses the user-assigned XKX) */
  alpha3: string;
  name: string;
  aliases: string[];
  region: CountryRegion;
  subregion: string;
  capital: string;
  lat: number;
  lng: number;
  population: number | null;
  flag: string;
  landlocked: boolean;
  /** Suggested map zoom that frames the country. */
  zoom: number;
  /** Land-border neighbours (ISO alpha-2), symmetric. */
  borders: string[];
}

export const COUNTRY_REGISTRY_META = (raw as unknown as { meta: Record<string, string> }).meta;
export const COUNTRY_RECORDS: readonly CountryRecord[] = (raw as unknown as { countries: CountryRecord[] }).countries;

/** Lower-case, accent-free, punctuation-free form used to match names and aliases. */
export const normalizeName = (s: string) =>
  s
    .normalize("NFD")
    .replace(/\p{M}+/gu, "")
    .toLowerCase()
    .replace(/[^\p{L}\p{N}]+/gu, " ")
    .trim();

const byCode = new Map(COUNTRY_RECORDS.map((c) => [c.code, c]));
const byAlpha3 = new Map(COUNTRY_RECORDS.map((c) => [c.alpha3, c]));
const byName = new Map<string, CountryRecord>();
for (const c of COUNTRY_RECORDS) {
  byName.set(normalizeName(c.name), c);
  for (const a of c.aliases) if (!byName.has(normalizeName(a))) byName.set(normalizeName(a), c);
}

/** Exact ISO alpha-2 lookup. */
export const getCountryRecord = (code: string | null | undefined): CountryRecord | undefined => (code ? byCode.get(code.trim().toUpperCase()) : undefined);

/** Resolves an ISO alpha-2, ISO alpha-3, canonical name or alias ("FI", "FIN", "Finland", "Suomi"). */
export function resolveCountry(input: string | null | undefined): CountryRecord | undefined {
  const s = (input ?? "").trim();
  if (!s) return undefined;
  const up = s.toUpperCase();
  if (up.length === 2 && byCode.has(up)) return byCode.get(up);
  if (up.length === 3 && byAlpha3.has(up)) return byAlpha3.get(up);
  return byName.get(normalizeName(s));
}

/** Country search: exact identity first, then names/aliases by prefix, then substring. Bounded. */
export function searchCountries(query: string, limit = 8): CountryRecord[] {
  const q = normalizeName(query);
  if (!q) return [];
  const exact = resolveCountry(query);
  const out: CountryRecord[] = exact ? [exact] : [];
  const seen = new Set(out.map((c) => c.code));
  const score = (c: CountryRecord): number => {
    const names = [c.name, ...c.aliases].map(normalizeName);
    if (names.some((n) => n.startsWith(q))) return 1;
    if (names.some((n) => n.split(" ").some((w) => w.startsWith(q)))) return 2;
    if (names.some((n) => n.includes(q))) return 3;
    return 9;
  };
  for (const c of [...COUNTRY_RECORDS].map((c) => ({ c, s: score(c) })).filter((x) => x.s < 9).sort((a, b) => a.s - b.s || a.c.name.localeCompare(b.c.name)).map((x) => x.c)) {
    if (seen.has(c.code)) continue;
    seen.add(c.code);
    out.push(c);
  }
  return out.slice(0, limit);
}

export const neighboursOf = (code: string): CountryRecord[] => (getCountryRecord(code)?.borders ?? []).map((b) => byCode.get(b)).filter((c): c is CountryRecord => !!c);

/** Every land-border pair once (for building the scoring adjacency map). */
export function landBorderPairs(): [string, string][] {
  const out: [string, string][] = [];
  for (const c of COUNTRY_RECORDS) for (const b of c.borders) if (c.code < b) out.push([c.code, b]);
  return out;
}
